### ISSUE TITLE
Sample of using InteractionRequest -- behaviors of modal dialog box

### ISSUE THREAD

**Issue by frankwwu** [PrismLibrary/Prism-Samples-Wpf#11]
I have two questions about using InteractionRequest for modal dialog box. I hope they are included in the sample.
1. How to make the dialog box always staying on top of its parent window?
2. How to eliminate the dialog box from the Windows status bar?

**Comment by brianlagunas** [comment]
The issue of the popup staying on top of its parent window has been fixed in the current code base.  Please submit an issue describing the behavior you expect for when a dialog should be shown in the task bar, and when it shouldn't be.  
https://github.com/PrismLibrary/Prism/issues

For now, you could use the WindowStyle property to set that.

**Comment by frankwwu** [comment]
Thanks, Brain! I have submitted the second issue. For the first one, can you point me to the link? I have tried the InteractivityQuickstart. It is not fixed or demoed in the sample. I can't find the related API update.
Thanks,
Frank
Date: Thu, 19 Nov 2015 18:25:48 -0800

**Comment by brianlagunas** [comment]
Like I said, this is fixed in the latest code base of Prism, not in any public NuGets.  So the samples are not updated yet because they rely on the current public NuGet packages.  There is no API change, it will automatically set the parent Window.

**Comment by frankwwu** [comment]
Got it! I can't rely on NuGet. I need to get the source code from github and build it. Thank you!
Frank

Date: Sat, 21 Nov 2015 10:18:42 -0800
